apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin
  namespace: httpbin
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/httpbin`) || PathPrefix(`/httpbin/`) || Host(`httpbin.local`)
      kind: Rule
      services:
        - name: httpbin
          port: 80
  tls: {}
