apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin
  namespace: httpbin
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/httpbin`) || PathPrefix(`/httpbin/`)
      kind: Rule
      middlewares:
        - name: strip-httpbin-prefix
      services:
        - name: httpbin
          port: 80
          scheme: http
    - match: Host(`httpbin.local`)
      kind: Rule
      services:
        - name: httpbin
          port: 80
          scheme: http
