apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
  namespace: nginx
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/nginx`) || PathPrefix(`/nginx/`)
      kind: Rule
      middlewares:
        - name: strip-nginx-prefix
      services:
        - name: nginx
          port: 80
          scheme: http
    - match: Host(`nginx.local`)
      kind: Rule
      services:
        - name: nginx
          port: 80
          scheme: http
