apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd # somehow this has to be argocd for the apps to be displayed in the ui
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    name: in-cluster
  sources:
    - chart: traefik
      repoURL: https://helm.traefik.io/traefik
      targetRevision: '27.0.2' # https://github.com/traefik/traefik-helm-chart/blob/v27.0.2/traefik/values.yaml
      # helm:
      #   valueFiles:
      #     - $base/resources/traefik/values/base/values.yaml
      #     - $base/resources/traefik/values/dsps/values.yaml
    # - repoURL: https://gitlab.com/mobivia/atu/operations/argocd-ng.git
    #   targetRevision: main
    #   ref: base
    # - repoURL: https://gitlab.com/mobivia/atu/operations/argocd-ng.git
    #   path: resources/traefik/manifests/base
    #   targetRevision: main
    # - repoURL: https://gitlab.com/mobivia/atu/operations/argocd-ng.git
    #   path: resources/traefik/manifests/dsps
    #   targetRevision: main
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: 'true'
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - PruneLast=true
