apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd # somehow this has to be argocd for the apps to be displayed in the ui
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    name: in-cluster
  sources:
    # Helm chart source
    - chart: traefik
      repoURL: https://helm.traefik.io/traefik
      targetRevision: '39.0.0'
      helm:
        valueFiles:
          - $values/infra/traefik/values/values.yaml
    # Git repo source for values files (referenced as $values)
    - repoURL: https://github.com/Fettah/monitoring-logging-stack.git
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: 'true'
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - PruneLast=true
